{
 "title": "Spark Cluster metrics Demo2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Workers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metrics_master_workers_Value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Workers alive",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_aliveWorkers_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers memory used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (metrics_worker_memUsed_MB_Number)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers cores used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (metrics_worker_coresUsed_Value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_master_waitingApps_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metrics_master_apps_Number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tasks completed vs failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by(application_id) (metrics_executor_failedTasks_total)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum by(application_id) (metrics_executor_activeTasks)",
     "legendFormat": "active"
    },
    {
     "expr": "sum by(application_id) (metrics_executor_completedTasks_total)",
     "legendFormat": "completed"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(metrics_worker_memFree_MB_Value)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}